name: Hello Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: List files BEFORE checkout
        run: ls -la

      - name: Download my code
        uses: actions/checkout@v4

      - name: List files AFTER checkout
        run: ls -la

      - name: Show .NET version
        run: dotnet --version
